### PR TITLE
Remove upper version constraint for Python

### PR DESCRIPTION
**Pull request by cdce8p**
Remove the upper version constraint to allow installs with Python 3.13.

### CODE REVIEW

**Comment by cdce8p** [comment]
@frwickst Would you mind taking a look at this one? Without it we'd have to disable the `Huum` integration for Python 3.13, see https://github.com/home-assistant/core/pull/129442.

If merged, please do a new release so we can update the version used by Home Assistant.

**Comment by frwickst** [comment]
Thank you for bringing this to my attention. Sorry, I could not make this happen before the 3.13 branch was merged. Things happened to fast for me to react. But I've merged your changes as part of a separate push with some other changes as well that changed the version in all places of the repo.

I'll close this, but your commit was cherry-picked so that you would still get the credit for the change 😄

**Comment by cdce8p** [comment]
> Sorry, I could not make this happen before the 3.13 branch was merged. Things happened to fast for me to react.

No problem. Opened https://github.com/home-assistant/core/pull/130527 in Home Assistant to update the version and add support for 3.13 back.

**Comment by frwickst** [comment]
Thank you @cdce8p !

**Pull request closed without merging**
